import I1 from "../../images/NY/1.jpg";
import I2 from "../../images/NY/2.jpg";
import I3 from "../../images/NY/3.jpg";
import I4 from "../../images/NY/4.jpg";
import I5 from "../../images/NY/5.jpg";
import I6 from "../../images/NY/6.jpg";
import I7 from "../../images/NY/7.jpg";
import I8 from "../../images/NY/8.jpg";
import I9 from "../../images/NY/9.jpg";
import I10 from "../../images/NY/10.jpg";
import I11 from "../../images/NY/11.jpg";
import I12 from "../../images/NY/12.jpg";
import I13 from "../../images/NY/13.jpg";
import I14 from "../../images/NY/14.jpg";
import I15 from "../../images/NY/15.jpg";
import I16 from "../../images/NY/16.jpg";
import I17 from "../../images/NY/17.jpg";
import I18 from "../../images/NY/18.jpg";
import I19 from "../../images/NY/19.jpg";
import I20 from "../../images/NY/20.jpg";
import I21 from "../../images/NY/21.jpg";
import I22 from "../../images/NY/22.jpg";
import I23 from "../../images/NY/23.jpg";
import I24 from "../../images/NY/24.jpg";
import I25 from "../../images/NY/25.jpg";
import I26 from "../../images/NY/26.jpg";
import I27 from "../../images/NY/27.jpg";
import I28 from "../../images/NY/28.jpg";
import I29 from "../../images/NY/29.jpg";
import I30 from "../../images/NY/30.jpg";
import I31 from "../../images/NY/31.jpg";
import I32 from "../../images/NY/32.jpg";
import I33 from "../../images/NY/33.jpg";
import I34 from "../../images/NY/34.jpg";
import I35 from "../../images/NY/35.jpg";
import I36 from "../../images/NY/36.jpg";
import I37 from "../../images/NY/37.jpg";
import I38 from "../../images/NY/38.jpg";
import I39 from "../../images/NY/39.jpg";
import I40 from "../../images/NY/40.jpg";
import I41 from "../../images/NY/41.jpg";
import I42 from "../../images/NY/42.jpg";
import I43 from "../../images/NY/43.jpg";

export const dataNewYork = [
  {
    id: 2,
    pic: I2,
    imgWidth: "16%",
    mTop: "20%",
    mRight: "8%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: "",
  },
  {
    id: 3,
    pic: I3,
    imgWidth: "24%",
    mTop: "-10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 5,
  },
  {
    id: 4,
    pic: I4,
    imgWidth: "24%",
    mTop: "",
    mRight: "4%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: -20,
  },
  {
    id: 5,
    pic: I5,
    imgWidth: "60%",
    mTop: "-20%",
    mRight: "",
    mBottom: "",
    mLeft: "2%",
    positionX: "",
    speed: -10,
  },
  {
    id: 6,
    pic: I6,
    imgWidth: "60%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    id: 7,
    pic: I7,
    imgWidth: "60%",
    mTop: "8%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 5,
  },
  {
    id: 8,
    pic: I8,
    imgWidth: "24%",
    mTop: "-16%",
    mRight: "12%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: "",
  },
  {
    id: 9,
    pic: I9,
    imgWidth: "24%",
    mTop: "-10%",
    mRight: "",
    mBottom: "",
    mLeft: "6%",
    positionX: "",
    speed: 0,
  },
  {
    id: 10,
    pic: I10,
    imgWidth: "64%",
    mTop: "-6%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 11,
    pic: I11,
    imgWidth: "40%",
    mTop: "4%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 0,
  },
  {
    id: 12,
    pic: I12,
    imgWidth: "58%",
    mTop: "-2%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 13,
    pic: I13,
    imgWidth: "40%",
    mTop: "-2%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 0,
  },
  {
    id: 14,
    pic: I14,
    imgWidth: "60%",
    mTop: "4%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 15,
    pic: I15,
    imgWidth: "60%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 0,
  },
  {
    id: 16,
    pic: I16,
    imgWidth: "50%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 17,
    pic: I17,
    imgWidth: "30%",
    mTop: "-10%",
    mRight: "",
    mBottom: "",
    mLeft: "6%",
    positionX: "",
    speed: 0,
  },
  {
    id: 18,
    pic: I18,
    imgWidth: "26%",
    mTop: "-20%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 19,
    pic: I19,
    imgWidth: "60%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 0,
  },
  {
    id: 20,
    pic: I20,
    imgWidth: "30%",
    mTop: "-10%",
    mRight: "6%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 21,
    pic: I21,
    imgWidth: "30%",
    mTop: "-10%",
    mRight: "",
    mBottom: "",
    mLeft: "-6%",
    positionX: "center",
    speed: 0,
  },
  {
    id: 22,
    pic: I22,
    imgWidth: "30%",
    mTop: "4%",
    mRight: "14%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 23,
    pic: I23,
    imgWidth: "14%",
    mTop: "",
    mRight: "6%",
    mBottom: "",
    mLeft: "30%",
    positionX: "",
    speed: 0,
  },
  {
    id: 24,
    pic: I24,
    imgWidth: "40%",
    mTop: "8%",
    mRight: "8%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 25,
    pic: I25,
    imgWidth: "30%",
    mTop: "-10%",
    mRight: "",
    mBottom: "",
    mLeft: "6%",
    positionX: "",
    speed: 0,
  },
  {
    id: 26,
    pic: I26,
    imgWidth: "30%",
    mTop: "-4%",
    mRight: "6%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 27,
    pic: I27,
    imgWidth: "50%",
    mTop: "4%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 0,
  },
  {
    id: 28,
    pic: I28,
    imgWidth: "30%",
    mTop: "6%",
    mRight: "",
    mBottom: "",
    mLeft: "8%",
    positionX: "",
    speed: 0,
  },
  {
    id: 29,
    pic: I29,
    imgWidth: "54%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 30,
    pic: I30,
    imgWidth: "34%",
    mTop: "2%",
    mRight: "",
    mBottom: "",
    mLeft: "14%",
    positionX: "",
    speed: 0,
  },
  {
    id: 31,
    pic: I31,
    imgWidth: "30%",
    mTop: "-6%",
    mRight: "8%",
    mBottom: "",
    mLeft: "14%",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 32,
    pic: I32,
    imgWidth: "34%",
    mTop: "6%",
    mRight: "",
    mBottom: "",
    mLeft: "14%",
    positionX: "",
    speed: 0,
  },
  {
    id: 33,
    pic: I33,
    imgWidth: "60%",
    mTop: "6%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 34,
    pic: I34,
    imgWidth: "60%",
    mTop: "6%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 0,
  },
  {
    id: 35,
    pic: I35,
    imgWidth: "50%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 36,
    pic: I36,
    imgWidth: "30%",
    mTop: "2%",
    mRight: "",
    mBottom: "",
    mLeft: "14%",
    positionX: "",
    speed: 0,
  },
  {
    id: 37,
    pic: I37,
    imgWidth: "30%",
    mTop: "-6%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 38,
    pic: I38,
    imgWidth: "36%",
    mTop: "2%",
    mRight: "",
    mBottom: "",
    mLeft: "14%",
    positionX: "",
    speed: 0,
  },
  {
    id: 39,
    pic: I39,
    imgWidth: "50%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 40,
    pic: I40,
    imgWidth: "30%",
    mTop: "2%",
    mRight: "",
    mBottom: "",
    mLeft: "14%",
    positionX: "",
    speed: 0,
  },
  {
    id: 41,
    pic: I41,
    imgWidth: "40%",
    mTop: "2%",
    mRight: "10%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
  {
    id: 42,
    pic: I42,
    imgWidth: "30%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "14%",
    positionX: "center",
    speed: 0,
  },
  {
    id: 43,
    pic: I43,
    imgWidth: "100%",
    mTop: "6%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 0,
  },
];
